#include <stdio.h>
#include "pico/stdlib.h"
#include "hardware/pio.h"
#include "hardware/clocks.h"

// header generated by pio_asm
//
#include "squarewave.pio.h"

const uint LED_PIN = 25;


int squarewave_init(PIO pio, uint pin_num, float freq_hz) {
    // claim unused state machine on specified PIO and configure
    // it to generate a squarewave on the specified GPIO pin

    // install program in PIO shared instruction space
    //
    uint squarewave_offset;
    if (pio_can_add_program (pio, &squarewave_program)) {
        squarewave_offset = pio_add_program (pio, &squarewave_program);
    } else {
        // couldn't add program
        return -1;
    }

    // claim unused state machine on PIO
    //
    int squarewave_sm = pio_claim_unused_sm(pio, true);
    if (squarewave_sm == -1) {
        // couldn't get a free state machine
        return -1;
    }

    // configure and enable state machine
    //
    squarewave_program_init (pio, squarewave_sm, squarewave_offset, pin_num, freq_hz);

    return squarewave_sm;
}


int main() {
    stdio_init_all();

    puts ("Initialising PIO state machine");

    PIO pio = pio0;
    uint output_gpio = LED_PIN;
    //uint output_gpio = 15;
    float freq_hz = 8333;       // square wave freq (min 500Hz)

    int squarewave_sm = squarewave_init(pio, output_gpio, freq_hz);
    if (squarewave_sm != -1) {
        puts ("OK");
    } else {
        puts ("Error");
    }

    // loop forever
    for (;;) {
        sleep_ms (1000);
    }
}